(() => {
const root=document.getElementById('game-root');let time=45,interval,selected=null,done=[],feedback='',ended=false;const tasks=[{name:'Find the real problem',icon:'01',area:'discover',cost:5,detail:'User interviews reveal that people want help choosing an agent, not more agents.'},{name:'Pick one useful job',icon:'02',area:'build',cost:5,detail:'You narrow the first experience to one clear customer outcome.'},{name:'Test with five people',icon:'03',area:'discover',cost:5,detail:'The test catches a confusing step before it reaches everyone.'},{name:'Ship the small version',icon:'04',area:'launch',cost:5,detail:'A limited release gives the team a safer way to learn.'},{name:'Add 50 more features',icon:'?!',area:'trap',cost:8,detail:'Scope explosion! More features took time without clarifying the experience.'},{name:'Buy a huge campaign',icon:'$',area:'trap',cost:8,detail:'People arrived—but the confusing journey still needs fixing.'}];
function el(tag,text,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n}function button(text,fn,cls){const n=el('button',text,cls);n.type='button';n.onclick=fn;return n}function stop(){clearInterval(interval)}
function intro(){stop();root.replaceChildren();const board=el('div',null,'launch-start');board.append(el('p','THE 45-SECOND PRODUCT LAUNCH','game-complete'),el('h3','Can you turn chaos into a launch?','game-question'),el('p','Pick a task. Send it to Discover, Build, or Launch. Complete four useful moves before the clock runs out. Watch out for shiny distractions.'));board.append(button('Let’s launch something',start,'game-primary'));root.append(board)}
function start(){stop();time=45;selected=null;done=[];feedback='Your inbox is overflowing. Find the first useful move.';ended=false;render();interval=setInterval(()=>{time--;const clock=root.querySelector('.launch-clock');if(clock)clock.textContent=time+'s';if(time<=0)finish(false);},1000)}
function render(){root.replaceChildren();const top=el('div',null,'game-top');top.append(el('span','SPRINT IN PROGRESS'),el('strong',time+'s','launch-clock'),button('Restart',start,'game-text-button'));root.append(top);root.append(el('p',`${done.filter(x=>x<4).length} / 4 useful moves completed`,'game-complete'));const grid=el('div',null,'launch-grid');const inbox=el('div',null,'launch-inbox');inbox.append(el('h3','The inbox'));tasks.forEach((task,i)=>{const completed=done.includes(i);const b=button('',()=>{if(completed){selected=null;feedback='Revisit: '+task.detail;render()}else{selected=i;render()}},'launch-task');b.setAttribute('aria-pressed',String(selected===i));b.append(el('span',completed?'✓':task.icon),el('strong',task.name+(completed?' · View again':'')));inbox.append(b)});grid.append(inbox);const lanes=el('div',null,'launch-lanes');[['discover','Discover','Understand what people need.'],['build','Build','Make the smallest useful thing.'],['launch','Launch','Get it into people’s hands.']].forEach(([id,title,desc])=>{const b=button('',()=>move(id),'launch-lane');b.disabled=selected===null;b.append(el('h3',title),el('p',desc),el('span',selected===null?'Pick a task first':'Send task here'));lanes.append(b)});grid.append(lanes);root.append(grid);const status=el('div',feedback,'game-feedback');status.setAttribute('role','status');root.append(status);const log=el('div',null,'launch-log');done.forEach(i=>log.append(el('span',(i<4?'✓ ':'! ')+tasks[i].name)));root.append(log);root.append(button('Skip the clock, explore my work',()=>{stop();location.hash='work'},'game-text-button'))}
function move(area){if(selected===null||ended)return;const i=selected,task=tasks[i];selected=null;if(task.area==='trap'){done.push(i);time=Math.max(0,time-task.cost);feedback=task.detail+' −8 seconds.'}else if(task.area!==area){time=Math.max(0,time-3);feedback='That move belongs in a different stage. Try again! −3 seconds.'}else{done.push(i);feedback=task.detail;if(i===1&&!done.includes(0))feedback+=' You’re building before discovery—test your assumption early.';if(done.filter(x=>x<4).length===2){time=Math.max(0,time-5);feedback+=' Surprise: launch scope changed. Keep the customer outcome clear. −5 seconds.'}}if(done.filter(x=>x<4).length===4)finish(true);else if(time<=0)finish(false);else render()}
function finish(won){ended=true;stop();root.replaceChildren();root.append(el('p',won?'LAUNCH COMPLETE':'TIME’S UP','game-complete'),el('h3',won?'You shipped through the chaos.':'The backlog won this round.','game-question'),el('p',won?`${time} seconds left. You discovered, focused, tested, and shipped.`:'Try a smaller scope. Start with the problem, then build and launch.'),el('p','In Jovita, narrowing a broad AI workspace into an agent marketplace made the product story clearer. Explore the actual case study below.','game-feedback'));root.append(button('Play again',start,'game-primary'));const a=el('a','See the Jovita story','game-text-button');a.href='#jovita';root.append(a)}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&interval&&!ended){stop();interval=null;feedback='Paused while you were away. Resume when you’re ready.';render();root.append(button('Resume sprint',()=>{interval=setInterval(()=>{time--;const c=root.querySelector('.launch-clock');if(c)c.textContent=time+'s';if(time<=0)finish(false)},1000);render()},'game-primary'))}});intro();
})();
